//Demonstrate error handling using try-except.

try:
print(x)
except:
print("something is wrong")print(tuple_2)
 
